# Site settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tacojs.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
gems:
   - jemoji
   - jekyll-redirect-from
future: true

# Collections
collections:
  posts:
    title: Posts
    output: true
  meetups:
    title: Meetups
    output: true
    permalink: "/meetup/:path"
    layout: meetup
    location: TBD
    address: 1234 Market Street
    intersection: 12th & Market
  media:
    title: Media
    output: true

# Metadata
keywords: "tacojs, taco, javascript, meetup, philadelphia, node.js, talks, developer, meetup.com, libertyjs"
google-fonts: "BioRhyme:700|Suez+One|Work+Sans:400,700"
google-fonts-subsets: "latin"
google-analytics: "UA-XXXXXXXX-1"

# Commonly used lingo
title: TacoJS
location: Philadelphia, PA, USA
email: hello@victorlourng.com
description: > # this means to ignore newlines until the next colon
  Jelly beans pie bear claw jelly beans marshmallow. Cookie ice cream icing oat cake jelly-o ice cream topping cotton candy. Brownie bonbon icing. Cake sugar plum tart jujubes cookie. Tiramisu tiramisu candy bear claw chocolate bar pastry. Biscuit chocolate tiramisu tiramisu. Sesame snaps danish dragée sugar plum carrot cake bonbon pastry fruitcake chocolate cake. Soufflé jelly beans toffee lollipop jujubes candy. Tiramisu lollipop chocolate cake chocolate bar donut cake. Gummies halvah sweet roll brownie gingerbread ice cream. Topping jelly beans croissant cake icing brownie apple pie cotton candy. Gingerbread oat cake cupcake bear claw brownie. Tart caramels cheesecake topping.
handle: TacoJS
twitter: tacojs_phl
github: tacojs
slack: "http://phillydev.org/"
